greeting:
  message: "hello"

quarkus:
  http:
    host: 0.0.0.0
    port: 8093
    access-log:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D'
    record-request-start-time: true
    root-path: '/api'
    cors:
      enabled: true
      methods: 'GET,POST,PUT, DELETE'
      headers: X-Custom
      origins: http://localhost

